#!/bin/bash

# Copyright (C) 2012 D.Furiya
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
 
#####
# Function Definition
#####
function commandInfo() {
    echo "Adb All devices installer Version 1.0.0"
    echo ""
    echo "device commands:"
    echo "  adball install [apkfile]"
    echo "  - push this package file to all devices and install those"
    echo "  adball uninstall [apkfile]"
    echo "  - remove this app package from all devices"
    echo ""

    status=1
}
# All device install process
function installCmd() {
    curNum=0
    deviceNum=${#deviceList[@]}
    for target in ${deviceList[@]}
    do
        echo Being installed... $((curNum+1))/$((deviceNum+1))
        echo "adb -s ${target} ${command} -r ${apkfile}"
        adb -s ${target} ${command} -r ${apkfile}
        echo ""
        curNum=$((curNum+1))
    done
}
# All device uninstall process
function uninstallCmd() {
    curNum=0
    deviceNum=${#deviceList[@]}
    for target in ${deviceList[@]}
    do
        echo Being uninstalled... $((curNum+1))/$((deviceNum+1))
        echo "adb -s ${target} ${command} ${packageName}"
        adb -s ${target} ${command} ${packageName}
        echo ""
        curNum=$((curNum+1))
    done
}
#####

status=0

if [ $# -ne 2 ];
then
    commandInfo
    exit $status
fi

adbpath=$(which adb)
if [ $? -ne 0 ];
then
    echo "adb is not found"
    echo ""
    exit $status
fi

IFS=$'\n'
command=$1
apkfile=$2
packageName=$(aapt dump badging test.apk | grep package | awk '{print $2}' | awk -F"'" '{print $2}')
deviceList=$(adb devices|grep -v List|awk '{print $1}')

# Support Command is install and uninstall
#if [ ${command} != "install" -a ${command} != "uninstall" ];
#then
#    commandInfo
#    exit $status
#fi

if [ ${#deviceList[@]} -eq 0 ];
then
    echo "Error: Device not found"
    status=1
    exit $status
fi

case ${command} in

"install")
    installCmd
;;
"uninstall")
    uninstallCmd
;;
*)
    commandInfo
    exit $status
;;
esac

exit $status